name: Arduino-lint
# https://github.com/arduino/arduino-lint-action/tree/main
on:
  push:
    branches:
      - main
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: false # update submit false
          compliance: specification # strict specification permissive
          project-type: sketch # sketch library platform package-index all
          recursive: true # false or true
          verbose: true # true or false
